name: BattleKits
main: battlekits\BattleKits
version: 1.0.4
author: Falkirks
api: [3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: POSTWORLD
softdepend: ["EconomyAPI", "PocketMoney"]
permissions:
 battlekits:
  default: op
  children:
   battlekits.use:
    default: op
   battlekits.listkits:
    default: true
   battlekits.sign:
    default: op
    children:
     battlekits.sign.use:
      default: true
     battlekits.sign.create:
      default: op
